<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ImagesProductsSeeder extends Seeder
{

    public function run(): void
    {
        DB::table('images_products')->insert([
            ['product_id' =>  1, 'image_id' => 1],
            ['product_id' =>  1, 'image_id' => 2],
            ['product_id' =>  1, 'image_id' => 3],
            ['product_id' =>  2, 'image_id' => 4],
            ['product_id' =>  3, 'image_id' => 5],
            ['product_id' =>  3, 'image_id' => 6],
            ['product_id' =>  4, 'image_id' => 7],
            ['product_id' =>  5, 'image_id' => 8],
            ['product_id' =>  6, 'image_id' => 9],
            ['product_id' =>  7, 'image_id' => 10],
            ['product_id' =>  8, 'image_id' => 11],
            ['product_id' =>  9, 'image_id' => 12],
            ['product_id' =>  10, 'image_id' => 13],
            ['product_id' =>  11, 'image_id' => 14],
            ['product_id' =>  12, 'image_id' => 15],
            ['product_id' =>  13, 'image_id' => 16],
            ['product_id' =>  13, 'image_id' => 17],
            ['product_id' =>  14, 'image_id' => 18],
            ['product_id' =>  14, 'image_id' => 19],
            ['product_id' =>  15, 'image_id' => 20],
            ['product_id' =>  16, 'image_id' => 22],
            ['product_id' =>  17, 'image_id' => 21],
            ['product_id' =>  18, 'image_id' => 23],
            ['product_id' =>  19, 'image_id' => 24],
            ['product_id' =>  19, 'image_id' => 25],
            ['product_id' =>  20, 'image_id' => 26],
            ['product_id' =>  21, 'image_id' => 27],
            ['product_id' =>  22, 'image_id' => 28],
            ['product_id' =>  23, 'image_id' => 29],
            ['product_id' =>  24, 'image_id' => 30],
            ['product_id' =>  25, 'image_id' => 31],
            ['product_id' =>  26, 'image_id' => 32],
            ['product_id' =>  27, 'image_id' => 33],
            ['product_id' =>  28, 'image_id' => 34],
            ['product_id' =>  29, 'image_id' => 35],
            ['product_id' =>  30, 'image_id' => 36],
            ['product_id' =>  31, 'image_id' => 37],
            ['product_id' =>  32, 'image_id' => 38],
            ['product_id' =>  33, 'image_id' => 39],
            ['product_id' =>  34, 'image_id' => 40],
            ['product_id' =>  35, 'image_id' => 41],
            ['product_id' =>  36, 'image_id' => 42],
            ['product_id' =>  37, 'image_id' => 43],
            ['product_id' =>  38, 'image_id' => 44],
            ['product_id' =>  39, 'image_id' => 45],
            ['product_id' =>  40, 'image_id' => 46],
            ['product_id' =>  41, 'image_id' => 47],
            ['product_id' =>  42, 'image_id' => 48],
            ['product_id' =>  43, 'image_id' => 49],
            ['product_id' =>  44, 'image_id' => 50],
            ['product_id' =>  45, 'image_id' => 51],
            ['product_id' =>  46, 'image_id' => 52],
            ['product_id' =>  46, 'image_id' => 53],
            ['product_id' =>  47, 'image_id' => 54],
            ['product_id' =>  48, 'image_id' => 55],
            ['product_id' =>  48, 'image_id' => 56],
            ['product_id' =>  49, 'image_id' => 57],
            ['product_id' =>  50, 'image_id' => 58],
            ['product_id' =>  51, 'image_id' => 59],
            ['product_id' =>  52, 'image_id' => 60],
            ['product_id' =>  53, 'image_id' => 61],
            ['product_id' =>  54, 'image_id' => 62],
            ['product_id' =>  55, 'image_id' => 63],
            ['product_id' =>  55, 'image_id' => 64],
            ['product_id' =>  56, 'image_id' => 65],
            ['product_id' =>  57, 'image_id' => 66],
            ['product_id' =>  58, 'image_id' => 67],
            ['product_id' =>  59, 'image_id' => 68],
            ['product_id' =>  60, 'image_id' => 69],
            ['product_id' =>  61, 'image_id' => 70],
            ['product_id' =>  62, 'image_id' => 71],
            ['product_id' =>  63, 'image_id' => 72],
            ['product_id' =>  64, 'image_id' => 73],
            ['product_id' =>  65, 'image_id' => 74],
            ['product_id' =>  66, 'image_id' => 75],
            ['product_id' =>  67, 'image_id' => 76],
            ['product_id' =>  68, 'image_id' => 77],
            ['product_id' =>  68, 'image_id' => 78],
            ['product_id' =>  69, 'image_id' => 79],
            ['product_id' =>  70, 'image_id' => 80],
            ['product_id' =>  71, 'image_id' => 81],
            ['product_id' =>  72, 'image_id' => 82],
            ['product_id' =>  73, 'image_id' => 83],
            ['product_id' =>  74, 'image_id' => 84],
            ['product_id' =>  75, 'image_id' => 85],
            ['product_id' =>  76, 'image_id' => 86],
            ['product_id' =>  77, 'image_id' => 87],
            ['product_id' =>  78, 'image_id' => 88],
            ['product_id' =>  79, 'image_id' => 89],
            ['product_id' =>  80, 'image_id' => 90],
            ['product_id' =>  80, 'image_id' => 91],
            ['product_id' =>  81, 'image_id' => 92],
            ['product_id' =>  82, 'image_id' => 93],
            ['product_id' =>  82, 'image_id' => 94],
            ['product_id' =>  83, 'image_id' => 95],
            ['product_id' =>  84, 'image_id' => 96],
            ['product_id' =>  85, 'image_id' => 97],
            ['product_id' =>  85, 'image_id' => 98],
            ['product_id' =>  86, 'image_id' => 99],
            ['product_id' =>  87, 'image_id' => 100],
            ['product_id' =>  88, 'image_id' => 101],
            ['product_id' =>  89, 'image_id' => 102],
            ['product_id' =>  89, 'image_id' => 103],
            ['product_id' =>  90, 'image_id' => 104],
            ['product_id' =>  91, 'image_id' => 105],
            ['product_id' =>  92, 'image_id' => 106],
            ['product_id' =>  93, 'image_id' => 107],
            ['product_id' =>  94, 'image_id' => 108],
            ['product_id' =>  95, 'image_id' => 109],
            ['product_id' =>  96, 'image_id' => 110],
            ['product_id' =>  97, 'image_id' => 111],
            ['product_id' =>  98, 'image_id' => 112],
            ['product_id' =>  99, 'image_id' => 113],
            ['product_id' =>  100, 'image_id' => 114],
            ['product_id' =>  101, 'image_id' => 115],
            ['product_id' =>  102, 'image_id' => 116],
            ['product_id' =>  103, 'image_id' => 117],
            ['product_id' =>  104, 'image_id' => 118],
            ['product_id' =>  105, 'image_id' => 119],
            ['product_id' =>  106, 'image_id' => 120],
            ['product_id' =>  107, 'image_id' => 121],
            ['product_id' =>  108, 'image_id' => 122],
            ['product_id' =>  109, 'image_id' => 123],
            ['product_id' =>  110, 'image_id' => 124],
            ['product_id' =>  111, 'image_id' => 125],
            ['product_id' =>  112, 'image_id' => 126],
            ['product_id' =>  113, 'image_id' => 127],
            ['product_id' =>  114, 'image_id' => 128],
            ['product_id' =>  115, 'image_id' => 129],
            ['product_id' =>  116, 'image_id' => 130],
            ['product_id' =>  116, 'image_id' => 131],
            ['product_id' =>  117, 'image_id' => 132],
            ['product_id' =>  118, 'image_id' => 133],
            ['product_id' =>  118, 'image_id' => 134],
            ['product_id' =>  119, 'image_id' => 135],
            ['product_id' =>  120, 'image_id' => 136],
            ['product_id' =>  121, 'image_id' => 137],
            ['product_id' =>  122, 'image_id' => 138],
            ['product_id' =>  122, 'image_id' => 139],
            ['product_id' =>  123, 'image_id' => 140],
            ['product_id' =>  124, 'image_id' => 141],
            ['product_id' =>  124, 'image_id' => 142],
            ['product_id' =>  125, 'image_id' => 143],
            ['product_id' =>  126, 'image_id' => 144],
            ['product_id' =>  126, 'image_id' => 145],
            ['product_id' =>  127, 'image_id' => 146],
            ['product_id' =>  127, 'image_id' => 147],

        ]);
    }
}
