<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ImagesSeeder extends Seeder
{

    public function run(): void
    {
        DB::table('images')->insert([
            ['path' => 'images/1.jpg'],
            ['path' => 'images/2.jpg'],
            ['path' => 'images/3.jpg'],
            ['path' => 'images/4.jpg'],
            ['path' => 'images/5.jpg'],
            ['path' => 'images/6.jpg'],
            ['path' => 'images/7.jpg'],
            ['path' => 'images/8.jpg'],
            ['path' => 'images/9.jpg'],
            ['path' => 'images/10.jpg'],
            ['path' => 'images/11.jpg'],
            ['path' => 'images/12.jpg'],
            ['path' => 'images/13.jpg'],
            ['path' => 'images/14.jpg'],
            ['path' => 'images/15.jpg'],
            ['path' => 'images/16.jpg'],
            ['path' => 'images/17.jpg'],
            ['path' => 'images/18.jpg'],
            ['path' => 'images/19.jpg'],
            ['path' => 'images/20.jpg'],
            ['path' => 'images/21.jpg'],
            ['path' => 'images/22.jpg'],
            ['path' => 'images/23.jpg'],
            ['path' => 'images/24.jpg'],
            ['path' => 'images/25.jpg'],
            ['path' => 'images/26.jpg'],
            ['path' => 'images/27.jpg'],
            ['path' => 'images/28.jpg'],
            ['path' => 'images/29.jpg'],
            ['path' => 'images/30.jpg'],
            ['path' => 'images/31.jpg'],
            ['path' => 'images/32.jpg'],
            ['path' => 'images/33.jpg'],
            ['path' => 'images/34.jpg'],
            ['path' => 'images/35.jpg'],
            ['path' => 'images/36.jpg'],
            ['path' => 'images/37.jpg'],
            ['path' => 'images/38.jpg'],
            ['path' => 'images/39.jpg'],
            ['path' => 'images/40.jpg'],
            ['path' => 'images/41.jpg'],
            ['path' => 'images/42.jpg'],
            ['path' => 'images/43.jpg'],
            ['path' => 'images/44.jpg'],
            ['path' => 'images/45.jpg'],
            ['path' => 'images/46.jpg'],
            ['path' => 'images/47.jpg'],
            ['path' => 'images/48.jpg'],
            ['path' => 'images/49.jpg'],
            ['path' => 'images/50.jpg'],
            ['path' => 'images/51.jpg'],
            ['path' => 'images/52.jpg'],
            ['path' => 'images/53.jpg'],
            ['path' => 'images/54.jpg'],
            ['path' => 'images/55.jpg'],
            ['path' => 'images/56.jpg'],
            ['path' => 'images/57.jpg'],
            ['path' => 'images/58.jpg'],
            ['path' => 'images/59.jpg'],
            ['path' => 'images/60.jpg'],
            ['path' => 'images/61.jpg'],
            ['path' => 'images/62.jpg'],
            ['path' => 'images/63.jpg'],
            ['path' => 'images/64.jpg'],
            ['path' => 'images/65.jpg'],
            ['path' => 'images/66.jpg'],
            ['path' => 'images/67.jpg'],
            ['path' => 'images/68.jpg'],
            ['path' => 'images/69.jpg'],
            ['path' => 'images/70.jpg'],
            ['path' => 'images/71.jpg'],
            ['path' => 'images/72.jpg'],
            ['path' => 'images/73.jpg'],
            ['path' => 'images/74.jpg'],
            ['path' => 'images/75.jpg'],
            ['path' => 'images/76.jpg'],
            ['path' => 'images/77.jpg'],
            ['path' => 'images/78.jpg'],
            ['path' => 'images/79.jpg'],
            ['path' => 'images/80.jpg'],
            ['path' => 'images/81.jpg'],
            ['path' => 'images/82.jpg'],
            ['path' => 'images/83.jpg'],
            ['path' => 'images/84.jpg'],
            ['path' => 'images/85.jpg'],
            ['path' => 'images/86.jpg'],
            ['path' => 'images/87.jpg'],
            ['path' => 'images/88.jpg'],
            ['path' => 'images/89.jpg'],
            ['path' => 'images/90.jpg'],
            ['path' => 'images/91.jpg'],
            ['path' => 'images/92.jpg'],
            ['path' => 'images/93.jpg'],
            ['path' => 'images/94.jpg'],
            ['path' => 'images/95.jpg'],
            ['path' => 'images/96.jpg'],
            ['path' => 'images/97.jpg'],
            ['path' => 'images/98.jpg'],
            ['path' => 'images/99.jpg'],
            ['path' => 'images/100.jpg'],
            ['path' => 'images/101.jpg'],
            ['path' => 'images/102.jpg'],
            ['path' => 'images/103.jpg'],
            ['path' => 'images/104.jpg'],
            ['path' => 'images/105.jpg'],
            ['path' => 'images/106.jpg'],
            ['path' => 'images/107.jpg'],
            ['path' => 'images/108.jpg'],
            ['path' => 'images/109.jpg'],
            ['path' => 'images/110.jpg'],
            ['path' => 'images/111.jpg'],
            ['path' => 'images/112.jpg'],
            ['path' => 'images/113.jpg'],
            ['path' => 'images/114.jpg'],
            ['path' => 'images/115.jpg'],
            ['path' => 'images/116.jpg'],
            ['path' => 'images/117.jpg'],
            ['path' => 'images/118.jpg'],
            ['path' => 'images/119.jpg'],
            ['path' => 'images/120.jpg'],
            ['path' => 'images/121.jpg'],
            ['path' => 'images/122.jpg'],
            ['path' => 'images/123.jpg'],
            ['path' => 'images/124.jpg'],
            ['path' => 'images/125.jpg'],
            ['path' => 'images/126.jpg'],
            ['path' => 'images/127.jpg'],
            ['path' => 'images/128.jpg'],
            ['path' => 'images/129.jpg'],
            ['path' => 'images/130.jpg'],
            ['path' => 'images/131.jpg'],
            ['path' => 'images/132.jpg'],
            ['path' => 'images/133.jpg'],
            ['path' => 'images/134.jpg'],
            ['path' => 'images/135.jpg'],
            ['path' => 'images/136.jpg'],
            ['path' => 'images/137.jpg'],
            ['path' => 'images/138.jpg'],
            ['path' => 'images/139.jpg'],
            ['path' => 'images/140.jpg'],
            ['path' => 'images/141.jpg'],
            ['path' => 'images/142.jpg'],
            ['path' => 'images/143.jpg'],
            ['path' => 'images/144.jpg'],
            ['path' => 'images/145.jpg'],
            ['path' => 'images/146.jpg'],
            ['path' => 'images/147.jpg'],
            
        ]);
    }
}
